### ISSUE TITLE
Add an example

### ISSUE THREAD

**Issue by AndreJesusBrito** [AndreJesusBrito/RegExpTemplate#1]
## Important note
Before anything else, this project is in very early stages and does not have full documentation yet. So, any question you might have you can ask down in the comments of this issue.

# Description

We want to have more examples to show possible use cases of this library.

The goal here is to make a new example based on the [url example](https://github.com/AndreJesusBrito/RegExpTemplate/blob/master/examples/url.js).

It doesn't need to as complex but must:
- follow the same format as the url example file (top info, comments, match examples).
- use `RegExpTemplate` for the construction, compile the result `RegExp` and make some test matches.
- be meaningful (close to a real case scenario) or help people better understand the library.

# How to
The easiest way to start is by creating a html file with the following code:

```html
<script src="https://cdn.jsdelivr.net/npm/@regexp-template/core/dist/regexp-template.min.js"></script>
<script>
  // your example code goes here
</script>
```

where you can create and test your example on your browser and any code editor.

Once the example is working and ready to merge, make a fork of the project and add your file with your example (this can be done directly on the GitHub webpage) and make a pull request.

Then you can wait us to review it: if something is not right, we will send you feedback so you can correct it.

Thanks for your time and good coding :)

**Comment by bgildson** [comment]
Hey @AndreJesusBrito , I would like to work on this, could you please assign it to me?

**Comment by AndreJesusBrito** [comment]
@bgildson sure.
